# .streamlit/secrets.toml
# Put this file locally only for testing.
# On Streamlit Cloud, add this in "Secrets" settings instead of committing.
OPENAI_API_KEY = "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"


