# .streamlit/secrets.toml
# Put this file locally only for testing; when deploying to Streamlit Cloud, add the secret in the UI.
OPENAI_API_KEY = "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"
