# .streamlit/secrets.toml
# Put this file locally only for testing.
# On Streamlit Cloud, add this in "Secrets" settings instead of committing.
OPENAI_API_KEY = "OPENAI_API_KEY = "sk-your-new-key"




