# .streamlit/secrets.toml
# Put this file locally only for testing.
# On Streamlit Cloud, add this in "Secrets" settings instead of committing.
OPENAI_API_KEY = "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"

